// Shop Name
export const GET_SHOP_NAME_REQUEST = 'GET_SHOP_NAME_REQUEST';
export const GET_SHOP_NAME_SUCCESS = 'GET_SHOP_NAME_SUCCESS';
export const GET_SHOP_NAME_FAIL = 'GET_SHOP_NAME_FAIL';

export const UPDATE_SHOP_NAME_REQUEST = 'UPDATE_SHOP_NAME_REQUEST';
export const UPDATE_SHOP_NAME_SUCCESS = 'UPDATE_SHOP_NAME_SUCCESS';
export const UPDATE_SHOP_NAME_FAIL = 'UPDATE_SHOP_NAME_FAIL';
export const UPDATE_SHOP_NAME_RESET = 'UPDATE_SHOP_NAME_RESET';

export const CUSTOMIZE_LOGO_REQUEST = 'CUSTOMIZE_LOGO_REQUEST';
export const CUSTOMIZE_LOGO_SUCCESS = 'CUSTOMIZE_LOGO_SUCCESS';
export const CUSTOMIZE_LOGO_FAIL = 'CUSTOMIZE_LOGO_FAIL';
export const CUSTOMIZE_LOGO_RESET = 'CUSTOMIZE_LOGO_RESET';

// Get Hero Slides
export const GET_HERO_SLIDES_REQUEST = 'GET_HERO_SLIDES_REQUEST';
export const GET_HERO_SLIDES_SUCCESS = 'GET_HERO_SLIDES_SUCCESS';
export const GET_HERO_SLIDES_FAIL = 'GET_HERO_SLIDES_FAIL';

// Add Hero Slide
export const ADD_HERO_SLIDE_REQUEST = 'ADD_HERO_SLIDE_REQUEST';
export const ADD_HERO_SLIDE_SUCCESS = 'ADD_HERO_SLIDE_SUCCESS';
export const ADD_HERO_SLIDE_FAIL = 'ADD_HERO_SLIDE_FAIL';
export const ADD_HERO_SLIDE_RESET = 'ADD_HERO_SLIDE_RESET';

// Update Hero Slide
export const UPDATE_HERO_SLIDE_REQUEST = 'UPDATE_HERO_SLIDE_REQUEST';
export const UPDATE_HERO_SLIDE_SUCCESS = 'UPDATE_HERO_SLIDE_SUCCESS';
export const UPDATE_HERO_SLIDE_FAIL = 'UPDATE_HERO_SLIDE_FAIL';
export const UPDATE_HERO_SLIDE_RESET = 'UPDATE_HERO_SLIDE_RESET';

// Delete Hero Slide
export const DELETE_HERO_SLIDE_REQUEST = 'DELETE_HERO_SLIDE_REQUEST';
export const DELETE_HERO_SLIDE_SUCCESS = 'DELETE_HERO_SLIDE_SUCCESS';
export const DELETE_HERO_SLIDE_FAIL = 'DELETE_HERO_SLIDE_FAIL';
export const DELETE_HERO_SLIDE_RESET = 'DELETE_HERO_SLIDE_RESET';

// Contact Info
export const GET_CONTACT_INFO_REQUEST = 'GET_CONTACT_INFO_REQUEST';
export const GET_CONTACT_INFO_SUCCESS = 'GET_CONTACT_INFO_SUCCESS';
export const GET_CONTACT_INFO_FAIL = 'GET_CONTACT_INFO_FAIL';

export const UPDATE_CONTACT_INFO_REQUEST = 'UPDATE_CONTACT_INFO_REQUEST';
export const UPDATE_CONTACT_INFO_SUCCESS = 'UPDATE_CONTACT_INFO_SUCCESS';
export const UPDATE_CONTACT_INFO_FAIL = 'UPDATE_CONTACT_INFO_FAIL';
export const UPDATE_CONTACT_INFO_RESET = 'UPDATE_CONTACT_INFO_RESET';

// Social Media
export const GET_SOCIAL_MEDIA_REQUEST = 'GET_SOCIAL_MEDIA_REQUEST';
export const GET_SOCIAL_MEDIA_SUCCESS = 'GET_SOCIAL_MEDIA_SUCCESS';
export const GET_SOCIAL_MEDIA_FAIL = 'GET_SOCIAL_MEDIA_FAIL';

export const UPDATE_SOCIAL_MEDIA_REQUEST = 'UPDATE_SOCIAL_MEDIA_REQUEST';
export const UPDATE_SOCIAL_MEDIA_SUCCESS = 'UPDATE_SOCIAL_MEDIA_SUCCESS';
export const UPDATE_SOCIAL_MEDIA_FAIL = 'UPDATE_SOCIAL_MEDIA_FAIL';
export const UPDATE_SOCIAL_MEDIA_RESET = 'UPDATE_SOCIAL_MEDIA_RESET';

// Clear Errors
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// About Us
export const GET_ABOUT_INFO_REQUEST = 'GET_ABOUT_INFO_REQUEST';
export const GET_ABOUT_INFO_SUCCESS = 'GET_ABOUT_INFO_SUCCESS';
export const GET_ABOUT_INFO_FAIL = 'GET_ABOUT_INFO_FAIL';

export const UPDATE_ABOUT_INFO_REQUEST = 'UPDATE_ABOUT_INFO_REQUEST';
export const UPDATE_ABOUT_INFO_SUCCESS = 'UPDATE_ABOUT_INFO_SUCCESS';
export const UPDATE_ABOUT_INFO_FAIL = 'UPDATE_ABOUT_INFO_FAIL';
export const UPDATE_ABOUT_INFO_RESET = 'UPDATE_ABOUT_INFO_RESET';

// Cookie consent constants
export const ACCEPT_COOKIES = 'ACCEPT_COOKIES';
export const REJECT_COOKIES = 'REJECT_COOKIES';
export const SET_COOKIE_CONSENT = 'SET_COOKIE_CONSENT';
