export const GET_SMTP_CONFIG_REQUEST = "GET_SMTP_CONFIG_REQUEST";
export const GET_SMTP_CONFIG_SUCCESS = "GET_SMTP_CONFIG_SUCCESS";
export const GET_SMTP_CONFIG_FAIL = "GET_SMTP_CONFIG_FAIL";

export const UPDATE_SMTP_CONFIG_REQUEST = "UPDATE_SMTP_CONFIG_REQUEST";
export const UPDATE_SMTP_CONFIG_SUCCESS = "UPDATE_SMTP_CONFIG_SUCCESS";
export const UPDATE_SMTP_CONFIG_FAIL = "UPDATE_SMTP_CONFIG_FAIL";
export const UPDATE_SMTP_CONFIG_RESET = "UPDATE_SMTP_CONFIG_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
