export const SAVE_STRIPE_KEYS_REQUEST = "SAVE_STRIPE_KEYS_REQUEST";
export const SAVE_STRIPE_KEYS_SUCCESS = "SAVE_STRIPE_KEYS_SUCCESS";
export const SAVE_STRIPE_KEYS_FAIL = "SAVE_STRIPE_KEYS_FAIL";

export const GET_STRIPE_KEYS_REQUEST = "GET_STRIPE_KEYS_REQUEST";
export const GET_STRIPE_KEYS_SUCCESS = "GET_STRIPE_KEYS_SUCCESS";
export const GET_STRIPE_KEYS_FAIL = "GET_STRIPE_KEYS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
