export const GET_WHATSAPP_REQUEST = "GET_WHATSAPP_REQUEST";
export const GET_WHATSAPP_SUCCESS = "GET_WHATSAPP_SUCCESS";
export const GET_WHATSAPP_FAIL = "GET_WHATSAPP_FAIL";

export const UPDATE_WHATSAPP_REQUEST = "UPDATE_WHATSAPP_REQUEST";
export const UPDATE_WHATSAPP_SUCCESS = "UPDATE_WHATSAPP_SUCCESS";
export const UPDATE_WHATSAPP_FAIL = "UPDATE_WHATSAPP_FAIL";
export const UPDATE_WHATSAPP_RESET = "UPDATE_WHATSAPP_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
